Updated installation routines

diff --git a/Stackscripts/devops b/Stackscripts/devops
--- a/Stackscripts/devops
+++ b/Stackscripts/devops
@@ -1,7 +1,7 @@
 #!/usr/bin/env bash
 #
 # Copyright (C) 2016 Xenith Consulting Limited
-# Author: Salim Badakhchani <sbadakhc@gmail.com>
+# Author: Salim Badakhchani <salimb@xenithconsulting.com>
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -25,47 +25,119 @@ set -x
 [[ $(id -u) == 0 ]] || echo -e "\n# This script requires root privileges to run"
 
 # Define logfile
-LOG="/root/install.log"
+LOG="/root/openshift.log"
 
-echo -e "########################################################################" > $LOG
-echo -e "Installing System..." >> $LOG
-echo -e "########################################################################\n" >> $LOG
-echo -e $(date) >> $LOG
-echo >> $LOG
+echo -e "########################################################################" > ${LOG}
+echo -e "Installing Openshift Origin..." >> ${LOG}
+echo -e "########################################################################\n" >> ${LOG}
+echo -e $(date) >> ${LOG}
+echo >> ${LOG}
 
 # Execution statements logicaly grouped into functions.
 
-function update_system {
-    echo -e "# Updating system..." >> $LOG
+disable_firewall () {
+    echo -e "# Disabling..." >> ${LOG}
+    systemctl stop iptables > /dev/null 2>&1 
+    systemctl stop ip6tables > /dev/null 2>&1
+    systemctl stop firewalld > /dev/null 2>&1
+}
+
+update_system () {
+    echo -e "# Updating system..." >> ${LOG}
     yum -y update > /dev/null 2>&1
 }
 
-function install_packages {
-    echo -e "# Installing packages..." >> $LOG
-    rpm -Uvh ftp://139.162.181.50/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm 
-    yum -y install docker git wget unzip net-tools bind bind-utils patch mlocate maven htop iftop curl tree
+install_packages () {
+    echo -e "# Installing packages..." >> ${LOG}
+    [[ -f "/etc/yum.repos.d/rpmforge.repo" ]] || rpm -Uvh ftp://139.162.181.50/rpmforge-release-0.5.3-1.el6.rf.x86_64.rpm
+    yum -y install git wget unzip net-tools patch mlocate maven htop iftop curl tree
+}
+
+create_profiles () {
+    echo "# Creating profile..." >> ${LOG}
+    cat > /etc/profile.d/custom.sh << 'EOF'
+# Prompt colors
+if [ `whoami` != "root" ]; then
+    PS1='\[\e[32m\][\u@\h \W]\$\[\e[0m\] '
+else
+    PS1='\[\e[31m\][\u@\h \W]\$\[\e[0m\] '
+fi
+
+# Aliases
+alias c='clear'
+alias h='history'
+alias m='less /var/log/messages'
+alias l='ll -has '
+alias n='netstat -vatulpn | grep'
+alias p='ps -A | grep'
+alias g='gvim'
+
+# Configure bash history 
+HISTSIZE='1000000'
+HISTIGNORE=' *:&:?:??'
+HISTCONTROL='ignoreboth:erasedups'
+
+export HISTSIZE HISTIGNORE HISTCONTROL
+
+# Turn on bash history options
+shopt -s histappend histreedit histverify
+
+# Sync term history
+history() {
+  history_sync
+  builtin history "$@"
+}
+
+history_sync() {
+  builtin history -a         
+  HISTFILESIZE=$HISTSIZE     
+  builtin history -c         
+  builtin history -r         
+}
+
+PROMPT_COMMAND=history_sync
+EOF
+
+    cat > /etc/profile.d/openshift.sh << 'EOF'
+export OPENSHIFT=/opt/openshift-origin-server-v1.3.0-alpha
+export OPENSHIFT_CLIENT=/opt/openshift-origin-client-tools-v1.3.0-alpha
+export OPENSHIFT_VERSION=v1.3.0-alpha
+export PATH=$OPENSHIFT:$PATH
+export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
+export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt
+EOF
+}
+
+setup_env () {
+    source /etc/profile.d/custom.sh
+    source /etc/profile.d/openshift.sh
+}
+
+add_hostname () {
+    [[ ! -z $(grep devops /etc/hosts) ]] || echo -e "139.162.173.55\tdevops00 devops00.oneincredible.com" >> /etc/hosts
 }
 
 install_docker () {
-    echo -e "# Patching docker..." >> $LOG
-    [[ -f "/etc/sysconfig/docker.orig" ]]; mv /etc/sysconfig/docker.orig /etc/sysconfig/docker
-    cp -p /etc/sysconfig/docker /etc/sysconfig/docker.orig
-    cat > /tmp/docker.patch << 'EOF'
---- /etc/sysconfig/docker	2015-12-10 17:57:32.000000000 -0500
-+++ /etc/sysconfig/docker	2016-03-31 02:28:46.835000000 -0400
-@@ -21,6 +21,7 @@
- # distributed, you can tell docker to not look for full authorization by
- # adding the registry to the INSECURE_REGISTRY line and uncommenting it.
- # INSECURE_REGISTRY='--insecure-registry'
-+INSECURE_REGISTRY='--insecure-registry 172.30.0.0/16'
- 
- # On an SELinux system, if you remove the --selinux-enabled option, you
- # also need to turn on the docker_transition_unconfined boolean.
+    echo -e "# Installing docker" >> ${LOG}
+    cat > /etc/yum.repos.d/docker.repo <<-'EOF'
+[dockerrepo]
+name=Docker Repository
+baseurl=https://yum.dockerproject.org/repo/main/centos/$releasever/
+enabled=1
+gpgcheck=1
+gpgkey=https://yum.dockerproject.org/gpg
 EOF
-(cd / && patch -p0) < /tmp/docker.patch
-rm -f /tmp/docker.patch
 
-echo -e "# Initialising docker..." >> $LOG
+yum -y install docker-engine
+
+[[ -d "/etc/systemd/system/docker.service.d " ]] || mkdir -p /etc/systemd/system/docker.service.d && cat > /etc/systemd/system/docker.service.d/override.conf << 'EOF'
+[Service] 
+ExecStart= 
+ExecStart=/usr/bin/docker daemon --storage-driver=overlay --insecure-registry 172.30.0.0/16 -H fd://
+EOF
+ 
+echo -e "# Initialising docker" >> ${LOG}
+systemctl daemon-reload
 systemctl enable docker
 systemctl restart docker
 
@@ -77,97 +149,170 @@ docker pull openshift/origin-docker-registry
 docker pull openshift/origin-haproxy-router
 }
 
-install_openshift () {
-    echo -e "# Installing openshift..." >> $LOG
-    mkdir /opt/openshift-origin-v1.1
-    chmod 755 /opt /opt/openshift-origin-v1.1
-    cd /opt/openshift-origin-v1.1
-    wget https://github.com/openshift/origin/releases/download/v1.1.3/openshift-origin-server-v1.1.3-cffae05-linux-64bit.tar.gz
-    tar -zxvf openshift-origin-server-*.tar.gz --strip-components 1
-    rm -f openshift-origin-server-*.tar.gz
+create_resolve () {
+echo -e "# Creating resolve file" >> ${LOG}
+cat > /etc/resolv.conf << 'EOF'
+# Generated by Kojak
+domain oneincredible.com
+search oneincredible.com
+nameserver 127.0.0.1
+nameserver 192.168.122.1
+EOF
+}
 
-    [[ -f /etc/profile.d/openshift.sh ]]; rm -f /etc/profile.d/openshift.sh
-cat > /etc/profile.d/openshift.sh << 'EOF'
-export OPENSHIFT=/opt/openshift-origin-v1.1
+install_openshift () {
+    echo -e "# Installing openshift" >> ${LOG}
+    mkdir /opt/openshift-origin-server-v1.3.0-alpha
+    [[ -f "/tmp/openshift-origin-server-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz" ]] || \
+    wget https://github.com/openshift/origin/releases/download/v1.3.0-alpha.2/openshift-origin-server-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz -P /tmp
+    tar -zxvf /tmp/openshift-origin-server-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz -C /opt/openshift-origin-server-v1.3.0-alpha/ --strip-components 1
+
+    cat > /etc/systemd/system/openshift-origin.service << 'EOF'
+[Unit]
+Description=Origin Master Service
+After=docker.service
+Requires=docker.service
+ 
+[Service]
+Restart=always
+RestartSec=10s
+ExecStart=/opt/openshift-origin-server-v1.3.0-alpha/openshift start
+WorkingDirectory=/opt/openshift-origin-server-v1.3.0-alpha
+ 
+[Install]
+WantedBy=multi-user.target
+EOF
+
+    cd $OPENSHIFT
+    $OPENSHIFT/openshift start --write-config=openshift.local.config 
+    sed -i 's/router.default.svc.cluster.local/oneincredible.com/' \
+    $OPENSHIFT/openshift.local.config/master/master-config.yaml
+    sed -i 's/0.0.0.0:53/127.0.0.1:8053/' \
+    $OPENSHIFT/openshift.local.config/master/master-config.yaml
+    chmod +r $OPENSHIFT/openshift.local.config/master/admin.kubeconfig
+    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig
+    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig
+
+    systemctl daemon-reload
+    systemctl enable openshift-origin
+    systemctl start openshift-origin
+
+    echo -e "# Configuring openshift" >> ${LOG}
+    source /etc/profile.d/openshift.sh
+
+    while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8443"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
+    echo -e "# Creating service accounts for registry and router" >> ${LOG}
+    oc login -u system:admin -n default
+    oc project default
+    echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"registry"}}' | oc create -f -
+    echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
+    [[ -f "/tmp/jq-linux64" ]] || wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64 -P /tmp
+    chmod +x /tmp/jq-linux64
+    oc get scc privileged -o json | /tmp/jq-linux64 '.users |= .+ ["system:serviceaccount:default:registry"]' | oc replace scc -f -
+    oc get scc privileged -o json | /tmp/jq-linux64 '.users |= .+ ["system:serviceaccount:default:router"]' | oc replace scc -f -
+	
+    echo -e "# Creating user roles" >> ${LOG}
+    oadm policy add-cluster-role-to-user cluster-admin admin
+	
+    echo -e "# Creating docker registry" >> ${LOG}
+    mkdir /opt/openshift-registry
+    chcon -Rt svirt_sandbox_file_t /opt/openshift-registry
+    chown root:root /opt/openshift-registry
+    oadm policy add-scc-to-user privileged -z registry 
+    oadm registry --service-account=registry --mount-host=/opt/openshift-registry
+	
+    echo -e "# Creating router" >> ${LOG}
+    oadm policy add-scc-to-user hostnetwork -z router
+    oadm router router --replicas=1 --service-account=router 
+    
+    
+    [[ -f "/tmp/openshift-ansible.git" ]] || cd /tmp && git clone https://github.com/openshift/openshift-ansible.git
+    cd /tmp/openshift-ansible/roles/openshift_examples/files/examples/latest/
+    for image in image-streams/image-streams-centos7.json; do cat $image | oc create -n openshift -f -; done
+    for image in db-templates/*.json; do cat $image | oc create -n openshift -f -; done
+    for image in quickstart-templates/*.json; do cat $image | oc create -n openshift -f -; done
+
+}
+
+install_openshift_client () {
+   
+    echo -e "# Installing openshift client" >> ${LOG}
+    mkdir /opt/openshift-origin-client-tools-v1.3.0-alpha
+    [[ -f "/tmp/openshift-origin-client-tools-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz" ]] || \
+    wget https://github.com/openshift/origin/releases/download/v1.3.0-alpha.2/openshift-origin-client-tools-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz -P /tmp
+    tar -zxvf /tmp/openshift-origin-client-tools-v1.3.0-alpha.2-983578e-linux-64bit.tar.gz -C /opt/openshift-origin-server-v1.3.0-alpha/ 
+
+}
+
+create_dnsmasq () {
+    echo -e "# Creating dnsmasq file" >> ${LOG}
+    [[ -f "/etc/dnsmasq.conf.orig" ]] || cp /etc/dnsmasq.conf /etc/dnsmasq.conf.orig 
+    cat > /etc/dnsmasq.conf << 'EOF'
+# Reverse DNS record for master
+host-record=master.oneincredible.com,139.162.173.55
+
+# Wildcard DNS for OpenShift Applications - Points to Router
+address=/oneincredible.com/139.162.173.55
+
+# Forward .local queries to SkyDNS
+server=/local/127.0.0.1#8053
+
+# Forward reverse queries for service network to SkyDNS.
+# This is for default OpenShift SDN - change as needed.
+server=/17.30.172.in-addr.arpa/127.0.0.1#8053
+
+# Do not read /etc/resolv.conf and forward requests
+# to nameservers listed there:
+no-resolv
+
+# Never forward plain names (without a dot or domain part)
+domain-needed
+
+# Never forward addresses in the non-routed address spaces.
+bogus-priv
+
+listen-address=127.0.0.1
+EOF
+}
+
+install_fabric8 () {
+    
+    [[ -f "/etc/profile.d/openshift" ]] || cat > /etc/profile.d/openshift.sh << 'EOF'
+export OPENSHIFT=/opt/openshift-origin-server-v1.3.0-alpha
+export OPENSHIFT_VERSION=v1.3.0-alpha
 export PATH=$OPENSHIFT:$PATH
 export KUBECONFIG=$OPENSHIFT/openshift.local.config/master/admin.kubeconfig
 export CURL_CA_BUNDLE=$OPENSHIFT/openshift.local.config/master/ca.crt
 EOF
 
-    echo -e "# Configuring openshift..." >> $LOG
-    chmod 644 /etc/profile.d/openshift.sh
-    . /etc/profile.d/openshift.sh
-    ./openshift start --write-config=openshift.local.config
-    chmod +r $OPENSHIFT/openshift.local.config/master/admin.kubeconfig
-    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig
-    chmod +r $OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig
-
-    echo -e "# Patching openshift..." >> $LOG
-        [[ -f "$OPENSHIFT/openshift.local.config/master/master-config.yaml.orig " ]]; mv $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig $OPENSHIFT/openshift.local.config/master/master-config.yaml
-        cp -p $OPENSHIFT/openshift.local.config/master/master-config.yaml $OPENSHIFT/openshift.local.config/master/master-config.yaml.orig 
-    cat > /tmp/openshift.patch << 'EOF'
---- /opt/openshift-origin-v1.1/openshift.local.config/master/master-config.yaml	2016-03-31 02:20:22.178000000 -0400
-+++ /opt/openshift-origin-v1.1/openshift.local.config/master/master-config.yaml	2016-03-31 02:28:22.731000000 -0400
-@@ -140,7 +140,7 @@
-     mcsLabelsPerProject: 5
-     uidAllocatorRange: 1000000000-1999999999/10000
- routingConfig:
--  subdomain: router.default.svc.cluster.local
-+  subdomain: example.com
- serviceAccountConfig:
-   limitSecretReferences: false
-   managedNames:
-EOF
-    (cd / && patch -p0) < /tmp/openshift.patch
-    rm -f /tmp/openshift.patch
-
-    echo -e "# Initialising openshift..." >> $LOG
-    nohup $OPENSHIFT/openshift --cors-allowed-origins='.*' start &
-
-    while ! timeout 1 bash -c "echo > /dev/tcp/localhost/8443"; do echo -e "# Retrying...please be patient" && sleep 12 ; done
-
-	echo -e "# Creating service accounts for registry and router..." >> $LOG
-	oc login -u system:admin -n default
-	oc project default
-	echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"registry"}}' | oc create -f -
-	echo '{"kind":"ServiceAccount","apiVersion":"v1","metadata":{"name":"router"}}' | oc create -f -
-	wget https://github.com/stedolan/jq/releases/download/jq-1.5/jq-linux64
-	chmod +x jq-linux64
-	oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:registry"]' | oc replace scc -f -
-	oc get scc privileged -o json | ./jq-linux64 '.users |= .+ ["system:serviceaccount:default:router"]' | oc replace scc -f -
-	oadm policy add-cluster-role-to-user cluster-admin admin
-	
-    echo -e "# Creating docker registry..." >> $LOG
-	mkdir /opt/openshift-registry
-	chown ${USER}.${USER} /opt/openshift-registry
-	oadm registry --credentials=$OPENSHIFT/openshift.local.config/master/openshift-registry.kubeconfig --service-account=registry --mount-host=/opt/openshift-registry
-	
-    echo -e "# Creating router..." >> $LOG
-	oadm router router --replicas=1 --credentials=$OPENSHIFT/openshift.local.config/master/openshift-router.kubeconfig --service-account=router
-	curl -sk https://raw.githubusercontent.com/openshift/origin/master/examples/image-streams/image-streams-centos7.json | oc create -n openshift -f -
-}
-
-install_fabric8 () {
-    echo -e "# Downloading gofabric8..." >> $LOG
+    source /etc/profile.d/openshift
+    echo -e "# Downloading gofabric8" >> ${LOG}
     cd /opt
-    wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.9/gofabric8-0.4.9-linux-amd64.tar.gz
     mkdir gofabric8
-    tar zxfv gofabric8-0.4.9-linux-amd64.tar.gz -C gofabric8/
+    [[ -f "/tmp/gofabric8-0.4.31-linux-amd64.tar.gz" ]] || \
+    wget https://github.com/fabric8io/gofabric8/releases/download/v0.4.31/gofabric8-0.4.31-linux-amd64.tar.gz -P /tmp
+    tar zxfv /tmp/gofabric8-0.4.31-linux-amd64.tar.gz -C /opt/gofabric8/
 
-    echo -e "# Downloading fabric8 templates..." >> $LOG
-    curl -o fabric8.zip http://repo1.maven.org/maven2/io/fabric8/forge/distro/distro/2.2.153/distro-2.2.153-templates.zip
-    unzip -d fabric8 fabric8.zip
+    echo -e "# Installing fabric8" >> ${LOG}
+    /opt/gofabric8/gofabric8 deploy --yes --namespace="default" --domain oneincredible.com
+    oc get oauthclient fabric8
 
-    echo -e "# Installing fabric8..." >> $LOG
-    /opt/gofabric8/gofabric8 deploy --namespace="default" --domain example.com --yes 
-    /opt/gofabric8/gofabric8 secrets --yes
+    echo -e "# Configure cd-pipeline" >> ${LOG}
+    /opt/gofabric8/gofabric8 pull cd-pipeline
 
-    echo -e "# Validate installaiton..." >> $LOG
+    echo -e "# Validate installaiton" >> ${LOG}
     /opt/gofabric8/gofabric8 validate --namespace="default"
 }
 
+disable_firewall
 update_system
 install_packages
+create_profiles
+setup_env
+add_hostname
 install_docker
+create_resolve
 install_openshift
+install_openshift_client
+create_dnsmasq
 install_fabric8
